version: '3.8'

services:
  web:
    build: ./services/backend
    volumes:
      - ./services/backend/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=TEST_USER
      - POSTGRES_PASSWORD=TEST_PASSWORD
      - POSTGRES_DB=foodgram

volumes:
  postgres_data: